version: '3.6'
services:
  agent1:
    image: teamblockchain/indy-agent:d64dddf
    ports:
      - "8094:8094"
    environment:
      - PORT=8094
    env_file:
      - ./Agent.env
  agent2:
    image: teamblockchain/indy-agent:d64dddf
    ports:
      - "8095:8095"
    environment:
      - PORT=8095
    env_file:
      - ./Agent.env
